const loginView=document.querySelector('#admin-login'),panel=document.querySelector('#admin-panel'),loginForm=document.querySelector('#admin-login-form'),loginError=document.querySelector('#admin-login-error'),globalError=document.querySelector('#global-error'),saveMessage=document.querySelector('#save-message'),grid=document.querySelector('#blob-grid'),profileSelect=document.querySelector('#profile-select'),finalSelect=document.querySelector('#final-photo'),saveButton=document.querySelector('#save-gallery');
const escapeHTML=(value='')=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
let state={users:[],user:null,blobs:[],gallery:[],hero_image_url:''};
async function request(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(data.error||'Ошибка соединения.'),{status:response.status});return data}
function pathnameFromUrl(value=''){try{return decodeURIComponent(new URL(value).pathname.slice(1))}catch{return value}}
function currentForBlob(blob){return state.gallery.find(item=>pathnameFromUrl(item.image_url)===blob.pathname)}
function positionOptions(selected=''){return['<option value="">Не использовать</option>',...Array.from({length:10},(_,i)=>`<option value="${i+1}" ${Number(selected)===i+1?'selected':''}>Место ${i+1}</option>`)].join('')}
function render(){
  profileSelect.innerHTML=state.users.map(user=>`<option value="${user.id}" ${Number(user.id)===Number(state.user.id)?'selected':''}>${escapeHTML(user.display_name)}</option>`).join('');
  finalSelect.innerHTML='<option value="">Не выбрана</option>'+state.blobs.map(blob=>`<option value="${escapeHTML(blob.pathname)}" ${pathnameFromUrl(state.hero_image_url)===blob.pathname?'selected':''}>${escapeHTML(blob.pathname)}</option>`).join('');
  grid.innerHTML=state.blobs.map((blob,index)=>{const current=currentForBlob(blob),isHeic=/\.heic$/i.test(blob.pathname),position=current?.position||(index<10?index+1:'');return `<article class="blob-card" data-pathname="${escapeHTML(blob.pathname)}"><div class="blob-preview">${isHeic?'<div class="heic-note">HEIC-фото<br>может не открыться во всех браузерах</div>':`<img src="/api/admin-photo?pathname=${encodeURIComponent(blob.pathname)}" alt="" loading="lazy">`}</div><div class="blob-fields"><span class="filename" title="${escapeHTML(blob.pathname)}">${escapeHTML(blob.pathname)}</span><div class="field-row"><label>Порядок<select class="position">${positionOptions(position)}</select></label><label>Заголовок<input class="caption" maxlength="160" value="${escapeHTML(current?.caption||'')}"></label></div><label>Маленький текст<textarea class="note" maxlength="500">${escapeHTML(current?.note||'')}</textarea></label>${isHeic?'<span class="heic-warning">Лучше заменить этот файл на JPG.</span>':''}</div></article>`}).join('');
  updateCount();
}
function updateCount(){const count=[...document.querySelectorAll('.position')].filter(select=>select.value).length;document.querySelector('#selection-count').textContent=`Выбрано: ${count} из 10`}
async function loadData(userId=''){globalError.textContent='';saveMessage.textContent='';grid.innerHTML='<p>Загружаю фотографии…</p>';try{state=await request(`/api/admin-data${userId?`?userId=${encodeURIComponent(userId)}`:''}`);loginView.hidden=true;panel.hidden=false;render()}catch(error){if(error.status===401){loginView.hidden=false;panel.hidden=true}else{globalError.textContent=error.message;grid.innerHTML=''}}}
loginForm.addEventListener('submit',async event=>{event.preventDefault();loginError.textContent='';const button=loginForm.querySelector('button');button.disabled=true;try{await request('/api/admin-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret:document.querySelector('#admin-secret').value})});loginForm.reset();await loadData()}catch(error){loginError.textContent=error.message}finally{button.disabled=false}});
profileSelect.addEventListener('change',()=>loadData(profileSelect.value));document.querySelector('#refresh-blobs').addEventListener('click',()=>loadData(profileSelect.value));grid.addEventListener('change',event=>{if(event.target.classList.contains('position'))updateCount()});
document.querySelector('#save-final-photo').addEventListener('click',async event=>{const message=document.querySelector('#final-photo-message'),button=event.currentTarget;message.textContent='';message.classList.remove('is-error');if(!finalSelect.value){message.textContent='Сначала выбери фотографию.';message.classList.add('is-error');return}button.disabled=true;button.firstChild.textContent='Сохраняю… ';try{await request('/api/admin-final',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:Number(profileSelect.value),pathname:finalSelect.value})});state.hero_image_url=finalSelect.value;message.textContent='Готово — это фото сохранено рядом с Роналду.'}catch(error){message.textContent=error.message;message.classList.add('is-error')}finally{button.disabled=false;button.firstChild.textContent='Сохранить только это фото '}});
saveButton.addEventListener('click',async()=>{globalError.textContent='';saveMessage.textContent='';const items=[...document.querySelectorAll('.blob-card')].map(card=>({pathname:card.dataset.pathname,position:Number(card.querySelector('.position').value),caption:card.querySelector('.caption').value,note:card.querySelector('.note').value})).filter(item=>item.position);const positions=items.map(item=>item.position);if(new Set(positions).size!==positions.length){globalError.textContent='Каждое место можно использовать только один раз.';return}saveButton.disabled=true;saveButton.firstChild.textContent='Сохраняю… ';try{await request('/api/admin-gallery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:Number(profileSelect.value),items,finalPath:finalSelect.value})});await loadData(profileSelect.value);saveMessage.textContent='Готово: фотографии и подписи сохранены в Neon.'}catch(error){globalError.textContent=error.message}finally{saveButton.disabled=false;saveButton.firstChild.textContent='Сохранить в Neon '}});
document.querySelector('#admin-logout').addEventListener('click',async()=>{await fetch('/api/admin-logout',{method:'POST'});panel.hidden=true;loginView.hidden=false});
loadData();
